### ISSUE TITLE
Error with CloudSQL Scanner 

### ISSUE THREAD

**Issue by kevensen** [forseti-security/forseti-security#3440]
Testing the 2.24 release and received the following error during `forseti scanner run`

```
{
  "serverMessage": "Error running scanner: CloudSqlAclScanner: 'Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n    scanner.run()\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/cloudsql_rules_scanner.py\", line 137, in run\n    self._output_results(all_violations)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/cloudsql_rules_scanner.py\", line 90, in _output_results\n    self._output_results_to_db(all_violations)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/base_scanner.py\", line 118, in _output_results_to_db\n    violation_access.create(violations, scanner_index_id)\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/services/scanner/dao.py\", line 233, in create\n    for violation in violations:\n  File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.24.0-py3.6.egg/google/cloud/forseti/scanner/scanners/cloudsql_rules_scanner.py\", line 70, in _flatten_violations\n    'project_id': violation.project_id}\nAttributeError: 'RuleViolation' object has no attribute 'project_id'\n'"
}
```

It looks like this was introduced with #3346.  The violation being reported used the project_id, but that attribute had not been added to the violation in _cloudsql_rules_engine.py_ .
